# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mangaplus.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mangaplus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmangaplus.proto\"<\n\x08Response\x12$\n\x07success\x18\x01 \x01(\x0b\x32\x0e.SuccessResultH\x00\x88\x01\x01\x42\n\n\x08_success\"S\n\rSuccessResult\x12.\n\x0ftitleDetailView\x18\x08 \x01(\x0b\x32\x10.TitleDetailViewH\x00\x88\x01\x01\x42\x12\n\x10_titleDetailView\"?\n\x0fTitleDetailView\x12\x1a\n\rnextTimeStamp\x18\x05 \x01(\x04H\x00\x88\x01\x01\x42\x10\n\x0e_nextTimeStampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mangaplus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE']._serialized_start=19
  _globals['_RESPONSE']._serialized_end=79
  _globals['_SUCCESSRESULT']._serialized_start=81
  _globals['_SUCCESSRESULT']._serialized_end=164
  _globals['_TITLEDETAILVIEW']._serialized_start=166
  _globals['_TITLEDETAILVIEW']._serialized_end=229
# @@protoc_insertion_point(module_scope)
